apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - client_pod.yaml
  - db_pod.yaml
  - gest_pod.yaml
  - serveur_pod.yaml
  - configs/db_env_config.yaml
  - configs/db_init.yaml
  - configs/volumes.yaml