version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent trois serveurs todo, trois clients, et un superviseur qui observe les tâches
    c1:
      # Premier client - Ajoute et retire des tâches automatiquement
      build:
        context: .
        dockerfile: Dockerfile.client

      container_name: arret03-c1
      image: arret03-client
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s1
      environment:
        - MONSERVEUR='s1'




    c2:
      image: arret03-client
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s2
      environment:
        - MONSERVEUR='s2'

    c3:
      image: arret03-client
      tty: true
      networks:
        - arret03-todo-net
      depends_on:
        - s3
      environment:
        - MONSERVEUR='s3'
      
    s1:
      # Premier serveur - Traite les demandes todo

      build:
        context: .
        dockerfile: Dockerfile.serveur

      container_name: arret03-s1
      image: arret03-serveur
      tty: true
      volumes:
        - "./tmp_todo1:/todo"
      networks:
        - arret03-todo-net
      environment:
        - MONNOM='c1'


    s2:
      tty: true
      image: arret03-serveur
      networks:
        - arret03-todo-net
      environment:
        - MONNOM='c2'

    s3:
      image: arret03-serveur
      tty: true
      networks:
        - arret03-todo-net
      environment:
        - MONNOM='c3'

    gestionnaire:
      build:
        context: .
        dockerfile: Dockerfile.gestionnaire
      container_name: arret03-gestionnaire
      image: arret03-gestionnaire
      networks:
        - arret03-todo-net
      tty: true
      environment:
        - MONSERVEUR='s1,s2,s3'
        - MONNOM='c1,c2,c3'

# Réseau par défaut
networks:
  arret03-todo-net:
