version: '3.2'

# Définition des services docker
services:
    # Ces services comprennent un serveur todo, un client, et un superviseur qui observe les tâches


    c1:

      # Client - Ajoute et retire des tâches automatiquement
      build:
        context: .
        dockerfile: Dockerfile.client

      container_name: arret02-c1
      image: arret02-client
      networks:
        - arret02-todo-net
      tty: true
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1'
        - MYNAME = 'c1'
         - MYSERVER = 'c1'

      
    s1:
      # Serveur - Traite les demandes todo
      build:
        context: .
        dockerfile: Dockerfile.serveur
      container_name: arret02-s1
      image: arret02-serveur
      networks:
        - arret02-todo-net
      tty: true
      volumes:
        - "./tmp_todo1:/todo"
      environment:
        - MONSERVEUR='c1'
        - MONNOM='s1'
        - MYNAME = 's1'
        - MYSERVER = 'c1'

    gestionnaire:
      # Permet d'observer les tâches en cours
      build:
        context: .
        dockerfile: Dockerfile.gestionnaire
      container_name: arret02-gestionnaire
      image: arret02-gestionnaire
      networks:
        - arret02-todo-net
      tty: true
      environment:
        - MONSERVEUR='s1'
        - MONNOM='gestionnaire'
        - MYNAME = 'gestionnaire'
        - MYSERVER = 'c1'

# Réseau par défaut
networks:
  arret02-todo-net:

