version: '3.2'

services:
  # Premier client - Ajoute et retire des tâches automatiquement
  c1:
    container_name: arret05-c1
    build:
      context: .
      dockerfile: Dockerfile.client
    image: arret05-client
    depends_on:
      - s1
    tty: true
    environment:
      - MONSERVEUR='s1'
    networks:
      - arret05-todo-net

  # Deuxième client - Ajoute et retire des tâches automatiquement
  c2:
    container_name: arret05-c2
    image: arret05-client
    depends_on:
      - s1
    environment:
      - MONSERVEUR='s1'
    tty: true
    networks:
      - arret05-todo-net

  # Troisième client - Ajoute et retire des tâches automatiquement
  c3:
    image: arret05-client
    tty: true
    container_name: arret05-c3
    depends_on:
      - s1
    environment:
      - MONSERVEUR='s1'

    networks:
      - arret05-todo-net

  # Premier serveur - Traite les demandes todo
  s1:
    container_name: arret05-s1
    build:
      context: .
      dockerfile: Dockerfile.serveur

    image: arret05-serveur
    tty: true
    depends_on:
    - db

    environment:
      - MONNOM='c1,c2,c3'
      - DB_HOST='db'

    networks:
      - arret05-todo-net

  # Permet d'observer les tâches en cours
  gestionnaire:
      container_name: arret05-gestionnaire
      build:
        context: .
        dockerfile: Dockerfile.gestionnaire

      networks:
        - arret05-todo-net
      image: a5-gestionnaire
      tty: true
      environment:
        - MONSERVEUR='s1'
        - MONNOM='c1,c2,c3'


  # Permet d'enregistrer les tâches
  db:
    build:
      context: ../base_img
      dockerfile: Dockerfile


    container_name: arret05-db
    image: postgres:15
    networks:
      - arret05-todo-net
    environment:
      - POSTGRES_PASSWORD=sergtsop
      - POSTGRES_USER=sergtsop
      - POSTGRES_DB=sergtsop

    volumes:
      - todo-db:/var/lib/postgresql/data
      - ./init_db/sql:/01_create_todo_schema.sql

volumes:
  todo-db:

# Réseau par défaut
networks:
  arret05-todo-net:

